### ISSUE TITLE
关于vue框架

### ISSUE THREAD

**Issue by love919849902** [dotnetlive/MStack.MainSite#41]
如果前端使用vue框架，就不会考虑使用jquery，因为jquery和vue的在对DOM进行处理的时候的思想是冲突的，但是如果使用bootstrap，怎么能处理掉bootstrap对jquery的依赖，是否可以考虑基于vue和bootstrap封装一套自己的UI框架？

**Comment by DukeCheng** [comment]
@love919849902 转移到dotnetlive的那个库

**Comment by ylvict** [comment]
@love919849902 Please refer to [VueStrap](https://yuche.github.io/vue-strap/) project, that will be a good workaround for this issue;
